# Generated by Django 5.2.16 on 2026-07-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PesanKontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subjek', models.CharField(max_length=200)),
                ('pesan', models.TextField()),
                ('dibaca', models.BooleanField(default=False)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pesan Kontak',
                'verbose_name_plural': 'Pesan Kontak',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='ProfilKampung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kampung', models.CharField(default='Kampung Sipias', max_length=100)),
                ('distrik', models.CharField(default='Elikobel', max_length=100)),
                ('kabupaten', models.CharField(default='Merauke', max_length=100)),
                ('provinsi', models.CharField(default='Papua Selatan', max_length=100)),
                ('luas_wilayah', models.CharField(blank=True, max_length=50)),
                ('jumlah_penduduk', models.PositiveIntegerField(default=0)),
                ('jumlah_kk', models.PositiveIntegerField(default=0, verbose_name='Jumlah KK')),
                ('sambutan_kepala', models.TextField(blank=True, verbose_name='Sambutan Kepala Kampung')),
                ('sejarah', models.TextField(blank=True)),
                ('visi', models.TextField(blank=True)),
                ('misi', models.TextField(blank=True)),
                ('letak_geografis', models.TextField(blank=True)),
                ('nama_kepala', models.CharField(blank=True, max_length=100, verbose_name='Nama Kepala Kampung')),
                ('foto_kepala', models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Foto Kepala Kampung')),
                ('foto_kantor', models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Foto Kantor Kampung')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telepon', models.CharField(blank=True, max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('tahun_berdiri', models.CharField(blank=True, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Kampung',
                'verbose_name_plural': 'Profil Kampung',
            },
        ),
        migrations.CreateModel(
            name='StrukturOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('pemerintah', 'Pemerintah Kampung'), ('bpk', 'Badan Permusyawaratan Kampung')], default='pemerintah', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='organisasi/')),
                ('urutan', models.PositiveSmallIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Struktur Organisasi',
                'verbose_name_plural': 'Struktur Organisasi',
                'ordering': ['urutan'],
            },
        ),
    ]
