# Generated by Django 5.2.16 on 2026-07-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilkampung',
            name='fasilitas_ibadah',
            field=models.PositiveIntegerField(default=1, verbose_name='Fasilitas Ibadah'),
        ),
        migrations.AddField(
            model_name='profilkampung',
            name='fasilitas_kesehatan',
            field=models.PositiveIntegerField(default=1, verbose_name='Fasilitas Kesehatan'),
        ),
        migrations.AddField(
            model_name='profilkampung',
            name='fasilitas_pendidikan',
            field=models.PositiveIntegerField(default=1, verbose_name='Fasilitas Pendidikan'),
        ),
        migrations.AddField(
            model_name='profilkampung',
            name='fasilitas_umum',
            field=models.PositiveIntegerField(default=1, verbose_name='Fasilitas Umum'),
        ),
        migrations.AddField(
            model_name='profilkampung',
            name='jumlah_laki',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Laki-laki'),
        ),
        migrations.AddField(
            model_name='profilkampung',
            name='jumlah_perempuan',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Perempuan'),
        ),
    ]
