# Generated by Django 5.2.16 on 2026-07-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profilkampung_fasilitas_ibadah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilkampung',
            name='peta_iframe',
            field=models.TextField(blank=True, help_text='Link embed Google Maps', verbose_name='Embed Code / URL Peta Google Maps'),
        ),
    ]
