# Generated by Django 5.2.16 on 2026-07-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profilkampung_peta_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilkampung',
            name='foto_fasilitas_ibadah',
            field=models.ImageField(blank=True, null=True, upload_to='fasilitas/', verbose_name='Foto Fasilitas Ibadah'),
        ),
        migrations.AddField(
            model_name='profilkampung',
            name='foto_fasilitas_kesehatan',
            field=models.ImageField(blank=True, null=True, upload_to='fasilitas/', verbose_name='Foto Fasilitas Kesehatan'),
        ),
        migrations.AddField(
            model_name='profilkampung',
            name='foto_fasilitas_pendidikan',
            field=models.ImageField(blank=True, null=True, upload_to='fasilitas/', verbose_name='Foto Fasilitas Pendidikan'),
        ),
        migrations.AddField(
            model_name='profilkampung',
            name='foto_fasilitas_umum',
            field=models.ImageField(blank=True, null=True, upload_to='fasilitas/', verbose_name='Foto Fasilitas Umum'),
        ),
    ]
