# Generated by Django 5.2.16 on 2026-07-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profilkampung_foto_fasilitas_ibadah_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoFasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('kesehatan', 'Fasilitas Kesehatan'), ('pendidikan', 'Fasilitas Pendidikan'), ('ibadah', 'Fasilitas Ibadah'), ('umum', 'Fasilitas Umum')], max_length=20)),
                ('judul', models.CharField(blank=True, help_text='Judul / nama fasilitas (opsional)', max_length=150)),
                ('foto', models.ImageField(upload_to='fasilitas/')),
                ('urutan', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto Fasilitas',
                'verbose_name_plural': 'Foto Fasilitas',
                'ordering': ['urutan', '-created_at'],
            },
        ),
    ]
