# Generated by Django 5.2.16 on 2026-07-27 23:18

import django_ckeditor_5.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriBerita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Kategori Berita',
                'verbose_name_plural': 'Kategori Berita',
            },
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('jenis', models.CharField(choices=[('berita', 'Berita'), ('pengumuman', 'Pengumuman'), ('kegiatan', 'Kegiatan')], default='berita', max_length=20)),
                ('ringkasan', models.TextField(blank=True, max_length=500, verbose_name='Ringkasan / Excerpt')),
                ('konten', django_ckeditor_5.fields.CKEditor5Field(config_name='extends', verbose_name='Konten Berita')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='berita/', verbose_name='Gambar Utama')),
                ('penulis', models.CharField(default='Admin Kampung Sipias', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Dipublikasikan')], default='draft', max_length=20)),
                ('tanggal_publish', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('unggulan', models.BooleanField(default=False, verbose_name='Jadikan Unggulan')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='berita.kategoriberita')),
            ],
            options={
                'verbose_name': 'Berita',
                'verbose_name_plural': 'Berita & Pengumuman',
                'ordering': ['-tanggal_publish'],
            },
        ),
    ]
