# Generated by Django 5.2.16 on 2026-07-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='unggulan',
            field=models.BooleanField(default=True, verbose_name='Jadikan Unggulan'),
        ),
    ]
