# Generated by Django 5.2.16 on 2026-07-29 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_alter_berita_unggulan'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoBerita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='berita/gallery/')),
                ('keterangan', models.CharField(blank=True, max_length=200, verbose_name='Keterangan Foto')),
                ('urutan', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan Tampil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('berita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_tambahan', to='berita.berita')),
            ],
            options={
                'verbose_name': 'Foto Berita',
                'verbose_name_plural': 'Foto Berita',
                'ordering': ['urutan', 'id'],
            },
        ),
    ]
