# Generated by Django 5.2.16 on 2026-07-27 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumGaleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('sampul', models.ImageField(blank=True, null=True, upload_to='galeri/sampul/', verbose_name='Foto Sampul Album')),
            ],
            options={
                'verbose_name': 'Album Galeri',
                'verbose_name_plural': 'Album Galeri',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='FotoGaleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('keterangan', models.TextField(blank=True)),
                ('foto', models.ImageField(upload_to='galeri/foto/')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('unggulan', models.BooleanField(default=False, verbose_name='Tampil di Beranda')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='galeri.albumgaleri')),
            ],
            options={
                'verbose_name': 'Foto Galeri',
                'verbose_name_plural': 'Foto Galeri',
                'ordering': ['-tanggal'],
            },
        ),
    ]
